apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-host-path
  labels:
    app: nginx-host-path
spec:
  replicas: 2 #how many
  selector:
    matchLabels:
      app: nginx-host-path
  template:
    metadata:
      labels:
        app: nginx-host-path
    spec:
      volumes:
        - name: nginx-host-stockage
          hostPath:
            path: /mnt/hostPath
            type: DirectoryOrCreate
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 3000 #see docker file
              name: "devops-project"
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-host-stockage
