---
- hosts: centos_server
  # Run commands as root
  become: true
  # Roles to be executed on these hosts
  roles:
    - role: application/install
      tags: install

    - role: application/healthchecks
      tags: check
