name: Main CI/CD

on:
  push:
    branches: [CI-CD-dev]
  pull_request:
    branches: [CI-CD-dev]

jobs:
  # CI part
  test:
    runs-on: ubuntu-latest

    # Define `working-directory` if you application is in a subfolder
    #defaults:
    #run:
    #working-directory: userapi
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        image: redis
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
        #with:
        #persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm install
      - run: npm ci
      - run: npm test

  deploy:
    needs: test # Requires CI part to be succesfully completed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Read instructions how to configure this action: https://github.com/marketplace/actions/deploy-to-heroku#getting-started
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "devops-projects" # Must be unique in Heroku
          heroku_email: "victor.barbe@edu.ece.fr" # Heroku account email
          #appdir: userapi # Define appdir if you application is in a subfolder
